# Generated by Django 5.2.1 on 2025-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notificationpreference_in_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='push',
            field=models.BooleanField(default=True),
        ),
    ]
