services:
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: backend:dev
    container_name: backend
    env_file:
      - .env
    ports:
      - "80:8000"
      - "5678:5678"
    networks:
      - backend_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Remove or comment out the volumes section if you want to use only develop/watch
    volumes:
      - ./src:/app/src
  
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          # path: .
          # target: /app
          ignore:
            - .venv/
            - .git/
            - __pycache__/
            - "*.pyc"
            - "*.pyo"
            - "*.pyd"
        - action: rebuild
          path: ./pyproject.toml
          target: /app/pyproject.toml
        - action: rebuild
          path: ./uv.lock
          target: /app/uv.lock
    tty: true
       
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:
  redis_data:

networks:
  backend_network:
    driver: bridge
    attachable: true
    name: backend_network
