# Generated by Django 5.2.1 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password Reset'), ('resend', 'Resend OTP'), ('account_delete', 'Account Delete'), ('account_restore', 'Account Restore'), ('account_deletion_confirmation', 'Account Deletion Confirmation')], default='signup', max_length=50),
        ),
    ]
