# Generated by Django 5.2.1 on 2025-06-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackedtoken',
            unique_together=set(),
        ),
    ]
