# Generated by Django 5.2.1 on 2025-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_alter_trackedtoken_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='trackedtoken',
            name='access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trackedtoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
